### ISSUE TITLE
Installing on windows

### ISSUE THREAD

**Issue by seancallahan88** [Robpol86/etaprogress#1]
Line 137 of setup.py  
    **get_metadata(os.path.join(NAME_FILE + ('/__init__.py' if PACKAGE else '.py')))

Should this be \ \ for windows? 

Installing on windows gives me this error: FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\sean\\appdata\\local\\temp\\pip_build_Sean\\etaprogress\\etaprogress/__init__.py'

**Comment by Robpol86** [comment]
I'll work on this next week.

**Comment by Robpol86** [comment]
Thanks for catching this. I've created a new version with a better setup.py file. Let me know if it's still broken.
